version: 2
jobs:
  build:
    working_directory: /go/src/github.com/wcharczuk/go-chart
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run:
          name: new-install
          command: make new-install
      - run:
          name: Continuous Integration
          command: make